# Generated by Django 2.2 on 2020-10-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_auto_20200916_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
