# Generated by Django 2.2 on 2020-10-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0006_remove_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
