# Generated by Django 2.2 on 2020-08-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailotp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='trans_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
