# Generated by Django 2.2 on 2020-08-18 08:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0002_cards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cards',
            new_name='Card',
        ),
    ]
