# Generated by Django 2.2 on 2020-08-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20200818_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
