# Generated by Django 2.2 on 2020-08-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_profileinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
