# Generated by Django 2.2 on 2020-08-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mrp', models.IntegerField()),
                ('deal_price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('is_nocost', models.BooleanField(default=False)),
                ('feature_1', models.CharField(max_length=255)),
                ('feature_2', models.CharField(max_length=255)),
                ('feature_3', models.CharField(max_length=255)),
                ('feature_4', models.CharField(max_length=255)),
                ('feature_5', models.CharField(max_length=255)),
                ('feature_6', models.CharField(max_length=255)),
                ('feature_7', models.CharField(max_length=255)),
                ('feature_8', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
