# Generated by Django 2.2 on 2020-08-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200801_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='pro_category',
            new_name='category',
        ),
    ]
