# Generated by Django 2.2 on 2020-08-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200801_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(null=True, upload_to='producs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(null=True, upload_to='producs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(null=True, upload_to='producs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(null=True, upload_to='producs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(null=True, upload_to='producs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_7',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_8',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
