# Generated by Django 2.2 on 2020-08-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200801_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='producs/<django.db.models.fields.CharField>'),
        ),
    ]
