# Generated by Django 2.2 on 2020-08-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200801_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='technical_details_electronics',
            new_name='electronic_components',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='technical_details_laptop',
            new_name='laptop',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='technical_details_mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='technical_details_sensors',
            new_name='sensors',
        ),
    ]
