# Generated by Django 2.2 on 2020-08-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200801_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
