# Generated by Django 2.2 on 2020-08-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_laptop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='ssd_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
