# Generated by Django 2.2 on 2020-08-02 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_seller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
