# Generated by Django 2.2 on 2020-08-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
    ]
