# Generated by Django 2.2 on 2020-08-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200802_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='processor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
