# Generated by Django 2.2 on 2020-08-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200802_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='battery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
