# Generated by Django 2.2 on 2020-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_mobile_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='producs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='producs/'),
        ),
    ]
