# Generated by Django 2.2 on 2020-08-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200802_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='ram_size',
        ),
    ]
