# Generated by Django 2.2 on 2020-08-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200802_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='property_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensors',
            name='property_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensors',
            name='property_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
