# Generated by Django 2.2 on 2020-08-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200802_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensor',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sensors',
            new_name='sensor',
        ),
    ]
