# Generated by Django 2.2 on 2020-08-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200802_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='audi_focus',
            new_name='audio_focus',
        ),
    ]
