# Generated by Django 2.2 on 2020-08-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200804_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='electronic_components',
            new_name='electronic_component',
        ),
    ]
