# Generated by Django 2.2 on 2020-08-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='is_published',
        ),
    ]
