# Generated by Django 2.2 on 2020-08-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20200822_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1', models.ImageField(blank=True, upload_to='banner/')),
                ('banner2', models.ImageField(blank=True, upload_to='banner/')),
                ('banner3', models.ImageField(blank=True, upload_to='banner/')),
                ('banner4', models.ImageField(blank=True, upload_to='banner/')),
                ('banner5', models.ImageField(blank=True, upload_to='banner/')),
                ('banner6', models.ImageField(blank=True, upload_to='banner/')),
                ('banner7', models.ImageField(blank=True, upload_to='banner/')),
                ('banner8', models.ImageField(blank=True, upload_to='banner/')),
            ],
        ),
    ]
